version: "3.9"

services:
  telegram-bot:
    container_name: telegram-bot
    working_dir: /app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    links:
      - redis
    networks:
      - app-network

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:latest
    ports:
      - '6379:6379'
    expose:
      - 6379
    networks:
      - app-network

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge