"""update mistakes

Revision ID: 232219f0479c
Revises: ad90d3cb955b
Create Date: 2025-06-22 17:20:26.885895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232219f0479c'
down_revision: Union[str, None] = 'ad90d3cb955b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mistake_types',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.add_column('mistakes', sa.Column('type_key', sa.String(), nullable=False))
    op.create_foreign_key(None, 'mistakes', 'mistake_types', ['type_key'], ['key'])
    op.drop_column('mistakes', 'group')
    op.drop_column('mistakes', 'subgroup')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistakes', sa.Column('subgroup', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mistakes', sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mistakes', type_='foreignkey')
    op.drop_column('mistakes', 'type_key')
    op.drop_table('mistake_types')
    # ### end Alembic commands ###
