"""update payments

Revision ID: 2ac73ab43c8c
Revises: a1dea4bf4802
Create Date: 2025-06-11 23:45:33.125538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ac73ab43c8c'
down_revision: Union[str, None] = 'a1dea4bf4802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('sub_id', sa.Integer(), nullable=False))
    op.drop_column('payments', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('type', postgresql.ENUM('sub', 'credits', name='paymenttype'), autoincrement=False, nullable=False))
    op.drop_column('payments', 'sub_id')
    # ### end Alembic commands ###
