"""update mistakes

Revision ID: 39c7d9dae2ff
Revises: 47118e423915
Create Date: 2025-05-30 16:51:20.254809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c7d9dae2ff'
down_revision: Union[str, None] = '47118e423915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistakes', sa.Column('subgroup', sa.String(), nullable=False))
    op.add_column('mistakes', sa.Column('incorrect', sa.String(), nullable=False))
    op.add_column('mistakes', sa.Column('correct', sa.String(), nullable=False))
    op.add_column('mistakes', sa.Column('example', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('mistakes', sa.Column('explanation', sa.TEXT(), nullable=False))
    op.drop_column('mistakes', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistakes', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('mistakes', 'explanation')
    op.drop_column('mistakes', 'example')
    op.drop_column('mistakes', 'correct')
    op.drop_column('mistakes', 'incorrect')
    op.drop_column('mistakes', 'subgroup')
    # ### end Alembic commands ###
