"""update dict

Revision ID: 73d70837b430
Revises: d726cc37381c
Create Date: 2025-11-11 02:11:06.751831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d70837b430'
down_revision: Union[str, None] = 'd726cc37381c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_dictionary_words', sa.Column('already_know', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_dictionary_words', 'already_know')
    # ### end Alembic commands ###
