"""ref

Revision ID: 7ba1af6ec134
Revises: 9a878efbb511
Create Date: 2025-05-30 13:06:50.643733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba1af6ec134'
down_revision: Union[str, None] = '9a878efbb511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('sub', 'credits', name='paymenttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('test', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('invited_by_id', sa.BIGINT(), nullable=True))
    op.add_column('users', sa.Column('credits_from_refs', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('paid_refs_percent', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('paid_refs_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'paid_refs_balance')
    op.drop_column('users', 'paid_refs_percent')
    op.drop_column('users', 'credits_from_refs')
    op.drop_column('users', 'invited_by_id')
    op.drop_table('payments')
    # ### end Alembic commands ###
