"""add column payments.is_autopaid

Revision ID: 839b3d4c13df
Revises: c4dcfebcc319
Create Date: 2025-06-27 19:58:56.772785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '839b3d4c13df'
down_revision: Union[str, None] = 'c4dcfebcc319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('sale', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payments', sa.Column('is_auto_paid', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('users', sa.Column('current_sub_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'subs', ['current_sub_id'], ['id'])
    op.drop_column('users', 'autopayment_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('autopayment_duration', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_sub_id')
    op.drop_column('payments', 'is_auto_paid')
    op.drop_table('subs')
    # ### end Alembic commands ###
