"""init spam

Revision ID: 8b52e8c3c367
Revises: e8e62e4e355b
Create Date: 2025-11-11 20:05:06.781922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b52e8c3c367'
down_revision: Union[str, None] = 'e8e62e4e355b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spam_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('keyboard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audience', sa.Enum('all', 'paid', 'not_paid', name='audience', schema='spam'), server_default='all', nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='spam'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spam_messages', schema='spam')
    # ### end Alembic commands ###
