"""delete mistakes

Revision ID: a1dea4bf4802
Revises: 39c7d9dae2ff
Create Date: 2025-06-01 19:36:52.636122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dea4bf4802'
down_revision: Union[str, None] = '39c7d9dae2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistakes', sa.Column('is_worked_out', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mistakes', 'is_worked_out')
    # ### end Alembic commands ###
