"""add-dictionary

Revision ID: ad90d3cb955b
Revises: 2ac73ab43c8c
Create Date: 2025-06-12 22:20:02.509608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad90d3cb955b'
down_revision: Union[str, None] = '2ac73ab43c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('ru_word', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_dictionary_words',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('learning_rate', sa.Integer(), server_default='0', nullable=False),
    sa.Column('can_be_mark_as_worked', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('is_worked', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['dictionary_words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_dictionary_words')
    op.drop_table('dictionary_words')
    # ### end Alembic commands ###
