"""autopayment

Revision ID: c4dcfebcc319
Revises: 232219f0479c
Create Date: 2025-06-24 15:22:35.326542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4dcfebcc319'
down_revision: Union[str, None] = '232219f0479c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_method_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_autopayment', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('users', sa.Column('autopayment_duration', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'autopayment_duration')
    op.drop_column('users', 'is_autopayment')
    op.drop_column('users', 'payment_method_id')
    # ### end Alembic commands ###
