"""add invitelinks

Revision ID: cf436693831c
Revises: 839b3d4c13df
Create Date: 2025-09-09 16:11:36.759229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf436693831c'
down_revision: Union[str, None] = '839b3d4c13df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_links',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('sale_percent', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.add_column('users', sa.Column('sale_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sale_percent')
    op.drop_table('invite_links')
    # ### end Alembic commands ###
