"""add dict_words.freq

Revision ID: d726cc37381c
Revises: d9e22107ef8e
Create Date: 2025-11-11 01:42:49.895513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd726cc37381c'
down_revision: Union[str, None] = 'd9e22107ef8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary_words', sa.Column('freq', sa.BIGINT(), nullable=True))
    op.drop_constraint(op.f('users_dictionary_words_user_id_fkey'), 'users_dictionary_words', type_='foreignkey')
    op.drop_constraint(op.f('users_dictionary_words_word_id_fkey'), 'users_dictionary_words', type_='foreignkey')
    op.create_foreign_key(None, 'users_dictionary_words', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'users_dictionary_words', 'dictionary_words', ['word_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_dictionary_words', type_='foreignkey')
    op.drop_constraint(None, 'users_dictionary_words', type_='foreignkey')
    op.create_foreign_key(op.f('users_dictionary_words_word_id_fkey'), 'users_dictionary_words', 'dictionary_words', ['word_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('users_dictionary_words_user_id_fkey'), 'users_dictionary_words', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dictionary_words', 'freq')
    # ### end Alembic commands ###
