"""updates

Revision ID: d9e22107ef8e
Revises: 4da276ed424f
Create Date: 2025-10-13 00:09:57.623314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e22107ef8e'
down_revision: Union[str, None] = '4da276ed424f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary_words', sa.Column('ru_words', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('dictionary_words', 'ru_word')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary_words', sa.Column('ru_word', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('dictionary_words', 'ru_words')
    # ### end Alembic commands ###
