"""init spam

Revision ID: e8e62e4e355b
Revises: 73d70837b430
Create Date: 2025-11-11 20:01:54.370259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e62e4e355b'
down_revision: Union[str, None] = '73d70837b430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
