"""add mistake user_message

Revision ID: fe6e58c27aef
Revises: 768c532a6498
Create Date: 2025-05-28 21:24:39.756507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6e58c27aef'
down_revision: Union[str, None] = '768c532a6498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistakes', sa.Column('user_message', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mistakes', 'user_message')
    # ### end Alembic commands ###
